// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2djxG50jP8VFw5WVLNIlt6qJaF_t_5w',
    appId: '1:845817648161:android:3ca3f8425e7c34f4f5ff60',
    messagingSenderId: '845817648161',
    projectId: 'versus-b95f6',
    storageBucket: 'versus-b95f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDem_q6hm5OCtXnFH7FGuRJoOBUi6WcpHQ',
    appId: '1:845817648161:ios:112a35eb8c65b24bf5ff60',
    messagingSenderId: '845817648161',
    projectId: 'versus-b95f6',
    storageBucket: 'versus-b95f6.firebasestorage.app',
    iosBundleId: 'com.example.versus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDem_q6hm5OCtXnFH7FGuRJoOBUi6WcpHQ',
    appId: '1:845817648161:ios:112a35eb8c65b24bf5ff60',
    messagingSenderId: '845817648161',
    projectId: 'versus-b95f6',
    storageBucket: 'versus-b95f6.firebasestorage.app',
    iosBundleId: 'com.example.versus',
  );
}
